### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by DracoClaw** [mr-miner1/better-settings#10]
Go to the Themes tab, and try searching for Manager or Quick CSS. The plugin will treat them as a setting option, only in that page strangely, pressing ENTER to search will crash the client outputing this error. After a reload the search is un-responsive until any setting is interacted with.

`VM875 C:\Users\Jake\Documents\powercord\src\fake_node_modules\powercord\injector\index.js:131 [Powercord:Injector] Failed to run injection "settingssearch" TypeError: Cannot read property 'props' of null
    at create (C:\Users\Jake\Documents\powercord\src\Powercord\plugins\better-settings\index.js:255:7)
    at t.<anonymous> (C:\Users\Jake\Documents\powercord\src\Powercord\plugins\better-settings\index.js:307:5)
    at C:\Users\Jake\Documents\powercord\src\fake_node_modules\powercord\injector\index.js:122:32
    at Array.forEach (<anonymous>)
    at Object._runInjections (C:\Users\Jake\Documents\powercord\src\fake_node_modules\powercord\injector\index.js:120:16)
    at t.render (C:\Users\Jake\Documents\powercord\src\fake_node_modules\powercord\injector\index.js:46:32)
    at e.dispatch (C:\Users\Jake\Documents\powercord\src\fake_node_modules\powercord\injector\index.js:39:52)
    at Object.open (C:\Users\Jake\Documents\powercord\src\fake_node_modules\powercord\injector\index.js:39:52)
    at HTMLInputElement.<anonymous> (C:\Users\Jake\Documents\powercord\src\Powercord\plugins\better-settings\index.js:141:30)
    at HTMLInputElement.listener (C:\Users\Jake\Documents\powercord\src\preload.js:154:14)`

https://draco-is.a-shitty.dev/f/VD0S5q.gif

**Comment by mr-miner1** [comment]
ill fix this in the next update aswell™️
